name: Vehicle manager

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-cli
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Deployment
        run: |
          script:
            mkdir -p ~/.ssh
            echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            rsync --exclude '.git' --exclude 'node_modules' --exclude 'vendor' --exclude '.env' --exclude '.github' \ -e "ssh -i ~/.ssh/deploy_key -p 7685 -o StrictHostKeyChecking=no" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/public_html/rubenderuijter.nl/vehicle-manager
            cd /public_html/rubenderuijter.nl/vehicle-manager
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate
            php artisan opt:cl
            npm install && npm run build
