name: Vehicle manager

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-cli
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PUBLIC_KEY }}" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            scp -r -i ~/.ssh/deploy_key -P 7685 ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/public_html/vehicle-manager
            ssh -i ~/.ssh/deploy_key -p 7685 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 
            cd /public_html/vehicle-manager
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate
            php artisan opt:cl
            npm install && npm run build
